services:
  - type: web
    name: paper-trading-app
    runtime: python
    buildCommand: ./build.sh
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true        # Render generates a random value on first deploy
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: paper-trading-db
          property: connectionString

databases:
  - name: paper-trading-db
    databaseName: paper_trading
    user: paper_trading
