# Generated by Django 6.0.3 on 2026-04-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0003_watchlistitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="trade",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
