# Generated by Django 6.0.3 on 2026-04-23 01:43

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0004_trade_notes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cash_balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("100000.00"), max_digits=12
                    ),
                ),
                (
                    "starting_balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("100000.00"), max_digits=12
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
