flowchart TD
    Home([Home page])
    Register([Register page])
    Login([Login page])
    Search([Search page])
    Trade([New trade page])
    History([Trade history page])
    Portfolio([Portfolio page])
    Admin([Admin page])

    Home --> Register
    Home --> Login
    Home --> Admin

    Register --> Login
    Login --> Home
    Login --> Search
    Login --> Trade
    Login --> History
    Login --> Portfolio
    Search --> Trade
    Trade --> History
    Trade --> Portfolio
    History --> Portfolio
    Portfolio --> Search
    Login --> Admin
